version: '3'
services:
#  vuejs:
#    container_name: frontend_vuejs
#    build: ./frontend
#    volumes:
#      - ./frontend:/app
#      - /app/node_modules
#    ports:
#      - "5173:5173"
#    depends_on:
#      - fastapi

  fastapi:
    container_name: backend_fastapi
    build: ./backend
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn main:app --host 0.0.0.0 --port 8000 --reload'
    volumes:
      - ./backend/app:/app
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flavor_forest
      POSTGRES_URL: localhost
      POSTGRES_PORT: 5432
      SECRET_KEY: SePEu1vMoDyVUSsmhB9Ruq_bGXdQejOF6b50H1TIW58
    depends_on:
      - db

  db:
    container_name: db_postgres
    build: ./postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init_tables:/docker-entrypoint-initdb.d/
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flavor_forest

volumes:
  postgres_data:
